### ISSUE TITLE
Immediate roadmap

### ISSUE THREAD

**Issue by daniloimparato** [dalmolingroup/easylayout#1]
**Etc:**
- [x] Document easylayout function [[1](https://rstudio.github.io/r-manuals/r-exts/Writing-R-documentation-files.html), [2](https://developer.r-project.org/Rds.html), [3](https://r-pkgs.org/man.html), [4](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)]
- [x] Write README

**R side:**
- [x] investigate weird precomputed positions

**Web app side:**
- [x] draw edges in editor mode
- [x] add button to enter editor mode
- [x] add button to open and close sidebar
- [x] add button to pause and resume
- [x] add button to send coordinates to r session
- [x] use actual node sizes and colors
- [x] control simulation through sidebar ui
- [x] entering edit mode should collapse sidebar

After text submission:
- [x] fix wrong position after moving groups in editor mode
- [ ] reintroduce non-lcc nodes in editor, pre-grouped by degree and bin packed ([check graphlayouts](https://github.com/schochastics/graphlayouts/blob/bfb4bb31bbf0425454d260e0fe6464f447aa0425/R/layout_stress.R#L14), [masonry](https://stackoverflow.com/questions/39239133/horizontal-ordered-bin-packing-of-svg-elements))

Etc
- https://stackoverflow.com/questions/58563989/how-paint-the-arrow-to-link-by-ngraph-pixi-with-pixi-js-with-webgl

**Comment by daniloimparato** [comment]
- https://github.com/dalmolingroup/easylayout/issues/4
- https://github.com/dalmolingroup/easylayout/issues/5
