### ISSUE TITLE
Post submission roadmap

### ISSUE THREAD

**Issue by daniloimparato** [dalmolingroup/easylayout#4]
**R side:**
- [ ] transform all vertex data to numeric
- [ ] run dimensionality reduction and get coordinates (MDS, t-sne, UMAP, hclust)
- [ ] returned layout matrix should contain hidden app metadata, but still behave like a matrix

**Web app side:**
- [ ] VivaGraphJS theta and gravity not updating in real-time [[1](https://github.com/anvaka/ngraph.forcelayout), [2](https://anvaka.github.io/ngraph.forcelayout/)]
- [ ] improve alpha controls during d3-force, cools down too fast [[1](https://blocks.roadtolarissa.com/steveharoz/8c3e2524079a8c440df60c1ab72b5d03)]
- [ ] simulation and editor should display nodes at the exact same screen coordinates [[1](http://fabricjs.com/interaction-with-objects-outside-canvas), [2](http://fabricjs.com/using-transformations), [3](https://github.com/anvaka/VivaGraphJS/issues/113), [4](https://github.com/fabricjs/fabric.js/issues/485#issuecomment-236451147)]
- [ ] fix switching layouts allowing simulation to run for a while [[1](https://github.com/anvaka/VivaGraphJS/issues/71)]
- [ ] reintroduce non-lcc nodes in editor, pre-grouped by degree and bin packed ([check graphlayouts](https://github.com/schochastics/graphlayouts/blob/bfb4bb31bbf0425454d260e0fe6464f447aa0425/R/layout_stress.R#L14), [masonry](https://stackoverflow.com/questions/39239133/horizontal-ordered-bin-packing-of-svg-elements))
- [ ] add cosmosgraph

Etc
- https://stackoverflow.com/questions/58563989/how-paint-the-arrow-to-link-by-ngraph-pixi-with-pixi-js-with-webgl
