### ISSUE TITLE
Nonpriority roadmap

### ISSUE THREAD

**Issue by daniloimparato** [dalmolingroup/easylayout#5]
Non priority:
- [ ] find old hex logo
- [ ] prevent individual rotation of objects when rotating selection [[1](https://stackoverflow.com/questions/29388776/how-to-keep-stable-objects-when-i-rotate-a-group-object-fabric-js), [2](https://stackblitz.com/edit/js-dd3jqv?file=index.js)]
- [ ] Reintroduce scaling for coordinates inside groups, but not scaling rects [[1](https://stackoverflow.com/questions/28497274/fabricjs-how-can-i-keep-fixed-size-on-group-elements-while-others-scaling)]
- [ ] selection box should be made more contrasting (dashed line + darker color)

**Comment by jvfe** [comment]
Maybe:

- [ ] Serve documentation through [pkgdown](https://github.com/r-lib/pkgdown) in GitHub pages? 

I believe having automated docs served on a separate website would increase visibility for the package and make it more accessible to people not familiar with GitHub.

I can work on this on a separate branch if you'd like

**Comment by daniloimparato** [comment]
@jvfe that would be lovely, take your time
